name: Deploy to staging

on:
  pull_request:
    branches: [ staging ]
    types:
      - closed

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ secrets.HEROKU_APP_NAME_STAGE }}

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged }}
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_STAGE }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
